language: c++
compiler: gcc
# ref: https://nbe.io/setting-up-travis-ci-to-compile-c-on-multiple/
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
    - make clean && make
